version: '3.8'

services:
  triton:
    image: nvcr.io/nvidia/tritonserver:23.01-py3
    environment:
      - MODEL_REPOSITORY=/models
    volumes:
      - ./model_repository:/models
    ports:
      #- "8000:8000"
      - "8001:8001"
      - "8002:8002"
    deploy:
      resources:
        limits:
          memory: 4g
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    command: ["tritonserver", "--model-repository=/models"]

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
