global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8080']

  - job_name: 'celery'
    static_configs:
      - targets: ['celery_app:9000']

  - job_name: "triton"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["triton:8002"]
