global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: 'api'
    metrics_path: "/metrics"
    static_configs:
      - targets: ['api:8080']

  - job_name: 'celery'
    static_configs:
      - targets: ['celery_app:9000']

  - job_name: "triton"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["triton:8002"]
